// Code generated by goctl. DO NOT EDIT!
// Source: oauth.proto

package server

import (
	"context"

	"micro/rpc/svs/oauth/internal/logic"
	"micro/rpc/svs/oauth/internal/svc"
	"micro/rpc/svs/oauth/oauth"
)

type OauthServer struct {
	svcCtx *svc.ServiceContext
}

func NewOauthServer(svcCtx *svc.ServiceContext) *OauthServer {
	return &OauthServer{
		svcCtx: svcCtx,
	}
}

//  Login 登录
func (s *OauthServer) Login(ctx context.Context, in *oauth.LoginReq) (*oauth.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
