// Code generated by goctl. DO NOT EDIT!
// Source: oauth.proto

package server

import (
	"context"

	"micro/rpc/svs/oauth/internal/logic"
	"micro/rpc/svs/oauth/internal/svc"
	"micro/rpc/svs/oauth/sys"
)

type SysServer struct {
	svcCtx *svc.ServiceContext
}

func NewSysServer(svcCtx *svc.ServiceContext) *SysServer {
	return &SysServer{
		svcCtx: svcCtx,
	}
}

//  Login 登录
func (s *SysServer) Login(ctx context.Context, in *sys.LoginReq) (*sys.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
