// Code generated by goctl. DO NOT EDIT!
// Source: oauth.proto

//go:generate mockgen -destination ./sys_mock.go -package sysclient -source $GOFILE

package sysclient

import (
	"context"

	"micro/rpc/svs/oauth/sys"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	LoginReq  = sys.LoginReq
	LoginResp = sys.LoginResp

	Sys interface {
		//  Login 登录
		Login(ctx context.Context, in *LoginReq) (*LoginResp, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

//  Login 登录
func (m *defaultSys) Login(ctx context.Context, in *LoginReq) (*LoginResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.Login(ctx, in)
}
