// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oauth.proto

package sys

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//user start---------------------
type LoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentAuthority     string   `protobuf:"bytes,2,opt,name=currentAuthority,proto3" json:"currentAuthority,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	AccessToken          string   `protobuf:"bytes,5,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,6,opt,name=AccessExpire,proto3" json:"AccessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,7,opt,name=RefreshAfter,proto3" json:"RefreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginResp) GetCurrentAuthority() string {
	if m != nil {
		return m.CurrentAuthority
	}
	return ""
}

func (m *LoginResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *LoginResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "sys.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "sys.loginResp")
}

func init() { proto.RegisterFile("oauth.proto", fileDescriptor_7ce0b12f599e9f07) }

var fileDescriptor_7ce0b12f599e9f07 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0x84, 0x40,
	0x10, 0x86, 0x03, 0x78, 0x08, 0x73, 0x7a, 0x31, 0x5b, 0x98, 0xcd, 0xd9, 0x10, 0x0a, 0x73, 0x31,
	0x91, 0x42, 0x9f, 0x80, 0x18, 0x3b, 0x63, 0x81, 0xf6, 0x06, 0x61, 0x4e, 0x36, 0x7a, 0x2c, 0xce,
	0xec, 0x46, 0x79, 0x60, 0xdf, 0xc3, 0xb0, 0x80, 0x39, 0xb5, 0xfc, 0xbf, 0x99, 0xfc, 0x33, 0xf9,
	0x60, 0xa9, 0x4b, 0x6b, 0x9a, 0xac, 0x23, 0x6d, 0xb4, 0x08, 0xb8, 0xe7, 0xf4, 0x06, 0xa2, 0x3b,
	0xfd, 0xa2, 0xda, 0x02, 0xdf, 0xc5, 0x19, 0xc4, 0x96, 0x91, 0x9e, 0xda, 0x72, 0x87, 0xd2, 0x4b,
	0xbc, 0x4d, 0x5c, 0x44, 0x03, 0xb8, 0x2f, 0x77, 0x28, 0xd6, 0x10, 0x75, 0x25, 0xf3, 0x87, 0xa6,
	0x5a, 0xfa, 0xe3, 0x6c, 0xce, 0xe9, 0x97, 0x07, 0xf1, 0xdb, 0xd8, 0xc2, 0x9d, 0x38, 0x85, 0x90,
	0x4d, 0x69, 0x2c, 0x4f, 0x1d, 0x53, 0x12, 0x17, 0x70, 0x52, 0x59, 0x22, 0x6c, 0x4d, 0x6e, 0x4d,
	0xa3, 0x49, 0x99, 0x7e, 0x6a, 0xfa, 0xc7, 0xc5, 0x0a, 0x7c, 0x55, 0xcb, 0x20, 0xf1, 0x36, 0x41,
	0xe1, 0xab, 0x7a, 0xb8, 0x3e, 0x7f, 0x22, 0x0f, 0xfe, 0x7c, 0x96, 0xc0, 0x32, 0xaf, 0x2a, 0x64,
	0x7e, 0xd4, 0xaf, 0xd8, 0xca, 0x85, 0x1b, 0xef, 0x23, 0x91, 0xc2, 0xd1, 0x18, 0x6f, 0x3f, 0x3b,
	0x45, 0x28, 0x43, 0xd7, 0xfb, 0x8b, 0x0d, 0x3b, 0x05, 0x6e, 0x09, 0xb9, 0xc9, 0xb7, 0x06, 0x49,
	0x1e, 0x8e, 0x3b, 0xfb, 0xec, 0xea, 0x12, 0x82, 0x87, 0x9e, 0xc5, 0x39, 0x2c, 0x9c, 0x33, 0x71,
	0x9c, 0x71, 0xcf, 0xd9, 0xec, 0x6f, 0xbd, 0x72, 0xf1, 0x47, 0xc4, 0x73, 0xe8, 0x3c, 0x5f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xff, 0x83, 0xc2, 0xcb, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysClient is the client API for Sys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysClient interface {
	// Login 登录
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type sysClient struct {
	cc *grpc.ClientConn
}

func NewSysClient(cc *grpc.ClientConn) SysClient {
	return &sysClient{cc}
}

func (c *sysClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysServer is the server API for Sys service.
type SysServer interface {
	// Login 登录
	Login(context.Context, *LoginReq) (*LoginResp, error)
}

// UnimplementedSysServer can be embedded to have forward compatible implementations.
type UnimplementedSysServer struct {
}

func (*UnimplementedSysServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterSysServer(s *grpc.Server, srv SysServer) {
	s.RegisterService(&_Sys_serviceDesc, srv)
}

func _Sys_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sys.Sys",
	HandlerType: (*SysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Sys_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth.proto",
}
